# -*- coding: utf-8 -*-
"""Copy of Assignment0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1erSExigyjlfn6BLzliZFwwgGE1vDjXSu

# Assignment 0
**Instrunctions for the assignment** \\

*   Open Google Colab: Begin by launching Google Colab and creating a new Python notebook.
*   Read Comments Carefully: Pay close attention to the comments provided within the codeblocks.


*   Code Block Completion: Fill in the codeblocks as per the instructions given in the comments.
*   Avoid Copying: Ensure that you understand the concepts and refrain from directly copying code from external sources.


*   Execute Codeblocks: Verify that each codeblock runs without errors by executing them.
*   Save and Submit: Once you've completed the assignment, save your notebook and follow the submission guidelines provided by your instructor.










**Notes:**

Encouragement: Take your time to understand the concepts behind each codeblock. This assignment aims to strengthen your Python programming skills. \\
Good Luck! : If you have any questions or require clarification on any aspect of the instructions, feel free to ask. \\
 \\

Best wishes for your assignment! These instructions are crafted to provide clarity and guidance as you work through the tasks in Google Colab.

## Getting Started
Solving these exercises will help make you a better programmer. Solve them in order, because each solution builds scaffolding, working code, and knowledge you can use on future problems. Read the directions carefully, and have fun!



*   To save your work to your Google Drive, go to File then "Save Copy in Drive".
*   Your own work will now appear in your Google Drive account!
*   Work on this copy as directed

## What to do when you don't know what to do next
- When the exercise asks you to reverse an list, the way forward is to search for "How to reverse a list in Python" in your favorite search engine.
- When the exercise asks you to check if a number is even, the way forward is to search for "how to check if a number is even in Python".
- When the exercise has you calculate the area of a circle, the way forward is to search for "how to calculate the area of a circle in Python" or "How to get pi in Python".

😀😀

## Basic Python Exercises

1. Create a new list from two list \\
list1 = [10, 20, 25, 30, 35] \\
list2 = [40, 45, 60, 75, 90]
"""

import numpy as np
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]

list3 = list1 + list2
print(list3)

"""2. Print multiplication table from 1 to 10"""

import numpy as np
for i in range(1,11):
  for j in range(1,11):
    print(i*j,end=" \t")
  print()

"""3. Print a downward Half-Pyramid Pattern

0 0 0 0 0   
0 0 0 0 <br>
0 0 0 <br>
0 0 <br>
0
"""

import numpy as np
for i in range(5,0,-1):
  for j in range(i):
    print(0,end=" ")
  print()

""" 4. Given the following assignment of the vegetables list, add "tomato" to the end of the list and sort them in alphabetical order.\
vegetables = ["eggplant", "broccoli", "carrot","cauliflower", "zucchini"]
"""

vegetables = ["eggplant", "broccoli", "carrot","cauliflower", "zucchini"]
vegetables.append("tomato")
vegetables.sort()
print(vegetables)

"""5. Write a function definition named is_odd that takes in a number and returns True or False if that number is odd."""

def odd(x):
  if x%2 != 0:
    return True
  else:
    return False

"""6. Write a function definition named mode that takes in sequence of numbers and returns the most commonly occuring value"""

def mode(x):
  count = {}
  for i in x:
    if i in count:
      count[i] += 1
    else:
      count[i] = 1
    return max(count,key.getitem(count))

"""## Numpy Exercises

Exercise 1: Create a 4X2 integer array and Prints its attributes \\
**Note:** The element must be a type of unsigned int16. \\
And print the following Attributes: –



1.   The shape of an array.
2.   Array dimensions.
3.   The Length of each element of the array in bytes.
"""

import numpy as np

arr = np.array([[1,2] , [3,4] , [5,6] , [7,8]])

print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

"""Exercise 2: Following is the provided numPy array. Return array of items by taking the third column from all rows \\
sampleArray = numpy.array ( [ [ 11 ,22, 33 ], [ 44, 55, 66 ], [ 77, 88, 99 ] ] )
"""

import numpy as np

sampleArray = np.array( [ [ 11, 22, 33] ,[44, 55, 66 ], [ 77, 88, 99 ]] )

print(sampleArray[:,2])

"""Exercise 3: Sort following NumPy array \\
Case 1: Sort array by the second row \\
Case 2: Sort the array by the second column
"""

import numpy as np

sampleArray = np.array([[28, 43, 56], [82, 21, 12], [50, 88, 66]])

sorted_indices = np.argsort(sampleArray[1, :])

sorted_by_second_row = sampleArray[:, sorted_indices]

print(sorted_by_second_row)

import numpy as np

sampleArray = np.array([[28, 43, 56], [82, 21, 12], [50, 88, 66]])

sorted_indices = np.argsort(sampleArray[:, 1])

sorted_by_second_column = sampleArray[sorted_indices, :]

print(sorted_by_second_column)

"""## Pandas Exercises
In this exercise, we are using Automobile Dataset for data analysis. This Dataset has different characteristics of an auto such as body-style, wheel-base, engine-type, price, mileage, horsepower, etc. \\
https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv

Exercise 1: From the given dataset print the first and last five rows.
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

stuff = pd.read_csv("Automobile_data.csv")

stuff.head(5)
stuff[-5:]

"""Exercise 2: Replace all column values which contain ?, n.a, or NaN with suitable values and print the updated dataset.:"""

import pandas as pd
import numpy as np

cny = pd.read_csv("Automobile_data.csv")
cny.replace(['?', 'n.a', np.nan], inplace=True)

print (cny)

"""Exercise 5: Count total cars per company and print them



"""

cny.company.value_counts()

"""## Matplotlib Exercises

Use the following CSV file for this exercise. Read this file using Pandas or NumPy or using in-built matplotlib function. \\
https://pynative.com/wp-content/uploads/2019/01/company_sales_data.csv

Exercise 1: Read Total profit of all months and show it using a line plot \\
Total profit data provided for each month. Generated line plot must include the following properties: –

X label name = Month Number \\
Y label name = Total profit \\
"""

from google.colab import files
upload = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt

# %matplotlib inline
sale = pd.read_csv("company_sales_data.csv")

plt.plot(sale['month_number'],sale['total_profit'])
plt.xlabel("Month Number")
plt.ylabel("Total profit")

"""Exercise : Read face cream and facewash product sales data and show it using the bar chart \\
The bar chart should display the number of units sold per month for each product. \\
Add a separate bar for each product in the same chart.
"""

b1 = plt.bar(sale['month_number'],sale['facecream'])
b2 = plt.bar(sale['month_number'],sale['facewash'])

plt.xlabel("Month Number")
plt.ylabel("Units sold per month")
plt.legend([b1,b2],['facecream','facewash'])